language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-ssl --white-list twitter.com facebook.com google.com linkedin.com shields.io paypal.me creativecommons.org sil.org choosealicense.com
